### ISSUE TITLE
run-hooks: Cannot open load file: No such file or directory, which-key

### ISSUE THREAD

**Issue by sameer1612** [LionyxML/emacs-kick#2]
after installation, this message comes up. 

to be fixed, to avoid first install panic

**Comment by LionyxML** [comment]
Thanks for reaching!

That's something strange.

Did you checked your Emacs version before running the install script?

https://github.com/LionyxML/emacs-kick/blob/master/README.md?plain=1#L42

In theory, Which key already comes pre-installed with Emacs > 30. 

You could force fetch changing this nil to t (https://github.com/LionyxML/emacs-kick/blob/master/init.el#L475), but I do not recommend doing so, more stuff will break if you're not on Emacs >30.

Please check your version with `emacs --version`.

Lastly, if the version is not the problem, you could provide more info: 
- your OS
- emacs version: `emacs --version`
- where you installed Emacs from
- running `emacs -nw --debug-init`, and pasting the error it spits on the *Messages*  buffer

**Comment by sameer1612** [comment]
You're right. I'm on 29.4. I'll upgrade to 30 and close this issue. 

Thanks
